/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromocaoRouteImport } from './routes/promocao'
import { Route as AprovadoRouteImport } from './routes/aprovado'
import { Route as IndexRouteImport } from './routes/index'

const PromocaoRoute = PromocaoRouteImport.update({
  id: '/promocao',
  path: '/promocao',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovadoRoute = AprovadoRouteImport.update({
  id: '/aprovado',
  path: '/aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/promocao': typeof PromocaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/promocao': typeof PromocaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprovado': typeof AprovadoRoute
  '/promocao': typeof PromocaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aprovado' | '/promocao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aprovado' | '/promocao'
  id: '__root__' | '/' | '/aprovado' | '/promocao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprovadoRoute: typeof AprovadoRoute
  PromocaoRoute: typeof PromocaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promocao': {
      id: '/promocao'
      path: '/promocao'
      fullPath: '/promocao'
      preLoaderRoute: typeof PromocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovado': {
      id: '/aprovado'
      path: '/aprovado'
      fullPath: '/aprovado'
      preLoaderRoute: typeof AprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprovadoRoute: AprovadoRoute,
  PromocaoRoute: PromocaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
